import Head from "next/head";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { Information } from "../components/Information";
import { Navbar } from "../components/Navbar";
import { SearchUser } from "../components/SearchUser";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-full bg-[#1E1E1E]">
      <Navbar />
      <Header />
      <SearchUser />
      <Information />
      <Footer />
    </div>
    </>
  );
}
